modLoader="javafml"
loaderVersion="${forgeLoaderVersionRange}"
issueTrackerURL="${githubUrl}/issues?q=is%3Aissue"
license="The MIT License (MIT)"

[[mods]]
modId="${configModId}"
version="${version}"
displayName="MezzConfig"
displayURL="${githubUrl}"
authors="${modAuthor}"
displayTest="IGNORE_SERVER_VERSION"
description='''
Lightweight client and server-authoritative config support for Minecraft mods.
'''

[[dependencies.${configModId}]]
    modId="forge"
    mandatory=true
    versionRange="${forgeVersionRange}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${configModId}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraftVersionRange}"
    ordering="NONE"
    side="BOTH"
