modLoader="javafml"
loaderVersion="${neoforgeLoaderVersionRange}"
license="The MIT License (MIT)"

[[mods]]
modId="mezz_config_gametests"
version="${version}"
displayName="MezzConfig NeoForge GameTests"
description='''Dedicated-server integration tests for MezzConfig.'''

[[dependencies.mezz_config_gametests]]
    modId="${configModId}"
    type="required"
    versionRange="[0,)"
    ordering="AFTER"
    side="SERVER"

[[dependencies.mezz_config_gametests]]
    modId="${neoforgeTestModId}"
    type="required"
    versionRange="[0,)"
    ordering="AFTER"
    side="SERVER"
