# Minecraft and loader pins for this build target.
modJavaVersion=17
minecraftVersion=1.19.2
minecraftVersionRange=[1.19.2]
forgeVersion=43.5.0
forgeLoaderVersionRange=[41,)
forgeVersionRange=[41.0.94,)
forgeTool=legacyModDevGradle
fabricLoaderVersion=0.19.4
fabricApiVersion=0.77.0+1.19.2
parchmentMinecraftVersion=1.19.2
parchmentVersionFabric=2022.11.27
loaders=Fabric,Forge
fabricLoaderVersionRange=>=0.16.3
fabricApiVersionRange=>=0.77.0+1.19.2
loomVersion=1.17.20
