# Minecraft and loader pins for this build target.
modJavaVersion=17
minecraftVersion=1.20.1
minecraftVersionRange=[1.20.1]
forgeVersion=47.4.23
forgeLoaderVersionRange=[47,)
forgeVersionRange=[47.0,)
fabricLoaderVersion=0.19.4
fabricApiVersion=0.92.11+1.20.1
parchmentMinecraftVersion=1.20.1
parchmentVersionFabric=2023.09.03
loaders=Fabric,Forge
fabricLoaderVersionRange=>=0.16.3
fabricApiVersionRange=>=0.92.11+1.20.1
loomVersion=1.17.20
