# Minecraft and loader pins for this build target.
modJavaVersion=21
minecraftVersion=1.21.1
minecraftVersionRange=[1.21.1]
neoforgeVersion=21.1.249
neoforgeLoaderVersionRange=[4,)
neoforgeVersionRange=[21.0.118-beta,)
fabricLoaderVersion=0.19.5
fabricLoaderVersionRange=>=0.16.3
fabricApiVersion=0.116.17+1.21.1
fabricApiVersionRange=>=0.116.5+1.21.1
parchmentMinecraftVersion=1.21.1
parchmentVersionFabric=2024.11.17
loaders=Fabric,NeoForge
loomVersion=1.17.20
