# Minecraft and loader pins for this build target.
modJavaVersion=25
minecraftVersion=26.1.2
minecraftVersionRange=[26.1.2]
neoforgeVersion=26.1.2.99
neoforgeLoaderVersionRange=[4,)
neoforgeVersionRange=[26.1.2.99,)
fabricLoaderVersion=0.19.4
fabricLoaderVersionRange=>=0.17.0
fabricApiVersion=0.155.2+26.1.2
fabricApiVersionRange=>=0.155.0+26.1.2
loaders=Fabric,NeoForge
loomVersion=1.17.20
