package net.mezzdev.config.file;

import net.mezzdev.filewatcher.FileWatcher;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class MezzConfigSettingsTest {
	@Test
	void loadUsesDefaultsWhenConfigFileDoesNotExist(@TempDir Path tempDir) {
		MezzConfigSettings settings = MezzConfigSettings.load(tempDir);

		assertTrue(settings.fileWatcherSettings().enabled());
		assertEquals(FileWatcher.DEFAULT_CHANGE_SETTLING_DELAY, settings.fileWatcherSettings().changeSettlingDelay());
		assertEquals(FileWatcher.DEFAULT_MISSING_DIRECTORY_RETRY_INTERVAL, settings.fileWatcherSettings().missingDirectoryRetryInterval());
	}

	@Test
	void loadReadsSettingsFromConfigFile(@TempDir Path tempDir) throws IOException {
		// Setup: write the same config path and value names generated by MezzConfig's internal schema.
		Path configPath = tempDir.resolve("mezz_config")
			.resolve("settings.ini");
		Files.createDirectories(configPath.getParent());
		Files.write(configPath, List.of(
			"[fileWatcher]",
			"enabled = false",
			"changeSettlingDelayMilliseconds = 25",
			"missingDirectoryRetryIntervalMilliseconds = 1000"
		));

		// Operation: load file watcher settings before the config manager creates the watcher.
		MezzConfigSettings settings = MezzConfigSettings.load(tempDir);

		// Assertions: startup settings are read from disk and can disable automatic file watching.
		assertFalse(settings.fileWatcherSettings().enabled());
		assertEquals(Duration.ofMillis(25), settings.fileWatcherSettings().changeSettlingDelay());
		assertEquals(Duration.ofMillis(1000), settings.fileWatcherSettings().missingDirectoryRetryInterval());
	}
}
