package net.mezzdev.config.file;

import net.mezzdev.filewatcher.FileWatcher;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.List;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class MezzConfigSettingsTest {
	@Test
	void loadUsesDevelopmentDefaultsWhenConfigFileDoesNotExist(@TempDir Path tempDir) {
		// Operation: load settings in a development environment without a settings file.
		MezzConfigSettings settings = MezzConfigSettings.load(tempDir, true);

		// Assertions: normal watcher defaults apply, and missing translation logging helps developers by default.
		assertTrue(settings.fileWatcherSettings().enabled());
		assertEquals(FileWatcher.DEFAULT_CHANGE_SETTLING_DELAY, settings.fileWatcherSettings().changeSettlingDelay());
		assertEquals(FileWatcher.DEFAULT_MISSING_DIRECTORY_RETRY_INTERVAL, settings.fileWatcherSettings().missingDirectoryRetryInterval());
		assertTrue(settings.logUntranslatedKeys());
	}

	@Test
	void loadDoesNotLogUntranslatedKeysByDefaultInProduction(@TempDir Path tempDir) {
		// Operation: load settings in a production environment without a settings file.
		MezzConfigSettings settings = MezzConfigSettings.load(tempDir, false);

		// Assertions: untranslated keys are quiet for regular players unless they opt in.
		assertFalse(settings.logUntranslatedKeys());
	}

	@Test
	void loadCanDisableUntranslatedKeyLoggingInDevelopment(@TempDir Path tempDir) throws IOException {
		// Setup: explicitly disable logging in the generated settings location.
		Path configPath = tempDir.resolve("mezz_config")
			.resolve("settings.ini");
		Files.createDirectories(configPath.getParent());
		Files.write(configPath, List.of(
			"[logging]",
			"logUntranslatedKeys = false"
		));

		// Operation: load the override in a development environment where the default would be enabled.
		MezzConfigSettings settings = MezzConfigSettings.load(tempDir, true);

		// Assertions: an explicit setting takes precedence over the environment default.
		assertFalse(settings.logUntranslatedKeys());
	}

	@Test
	void loadReadsSettingsFromConfigFile(@TempDir Path tempDir) throws IOException {
		// Setup: write the same config path, categories, and value names generated by MezzConfig's internal schema.
		Path configPath = tempDir.resolve("mezz_config")
			.resolve("settings.ini");
		Files.createDirectories(configPath.getParent());
		Files.write(configPath, List.of(
			"[fileWatcher]",
			"enabled = false",
			"changeSettlingDelayMilliseconds = 25",
			"missingDirectoryRetryIntervalMilliseconds = 1000",
			"[logging]",
			"logUntranslatedKeys = true"
		));

		// Operation: load settings before the config manager is created.
		MezzConfigSettings settings = MezzConfigSettings.load(tempDir, false);

		// Assertions: startup settings override both production and file-watching defaults.
		assertFalse(settings.fileWatcherSettings().enabled());
		assertEquals(Duration.ofMillis(25), settings.fileWatcherSettings().changeSettlingDelay());
		assertEquals(Duration.ofMillis(1000), settings.fileWatcherSettings().missingDirectoryRetryInterval());
		assertTrue(settings.logUntranslatedKeys());
	}

	@Test
	void loadUsesPackDefaultsAndPlayerOverrides(@TempDir Path tempDir) throws IOException {
		UUID playerId = UUID.fromString("12345678-1234-1234-1234-123456789abc");
		Path configDir = tempDir.resolve("mezz_config");
		Files.createDirectories(configDir);
		Files.write(configDir.resolve("settings.ini"), List.of(
			"[fileWatcher]",
			"enabled = false",
			"[logging]",
			"logUntranslatedKeys = true"
		));
		Path playerConfigPath = configDir.resolve("players")
			.resolve(playerId.toString())
			.resolve("settings.ini");
		Files.createDirectories(playerConfigPath.getParent());
		Files.write(playerConfigPath, List.of(
			"[logging]",
			"logUntranslatedKeys = false"
		));

		MezzConfigSettings settings = MezzConfigSettings.load(tempDir, playerId, false);

		assertFalse(settings.fileWatcherSettings().enabled());
		assertFalse(settings.logUntranslatedKeys());
	}
}
