modLoader="javafml"
loaderVersion="${forgeLoaderVersionRange}"
issueTrackerURL="${githubUrl}/issues?q=is%3Aissue"
license="The MIT License (MIT)"

[[mods]]
modId="${configApiModId}"
version="${version}"
displayName="Mezz Config API"
displayURL="${githubUrl}"
authors="${modAuthor}"
description='''
Shared config API for Minecraft mods.
'''

[[dependencies.${configApiModId}]]
    modId="forge"
    mandatory=true
    versionRange="${forgeVersionRange}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${configApiModId}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraftVersionRange}"
    ordering="NONE"
    side="BOTH"
